---
title: "Final Project"
author: "David Esposto"
date: "2022-11-22"
output: html_document
---

```{r}
set.seed(99)
mushroomData = read.csv("mushroom.csv", sep = ';')
head(mushroomData)

library (rpart)

num_samples = dim(mushroomData)[1]
sampling.rate = 0.8
training = sample(1:num_samples, sampling.rate*num_samples, replace= FALSE)
trainingSet = subset(mushroomData[training, ])
testing = setdiff(1:num_samples,training)
testingSet = subset(mushroomData[testing, ])

decTreeModel = rpart(class~cap.diameter+cap.shape+cap.surface+cap.color+does.bruise.or.bleed+gill.attachment+gill.spacing+gill.color+stem.height+stem.width+stem.root+stem.surface+stem.color+has.ring+ring.type+spore.print.color+habitat+season,data=trainingSet)

plot(decTreeModel, margin=0.1)
text(decTreeModel)

plotcp(decTreeModel)

pruned_decTreeModel = prune(decTreeModel, cp=0.02)
plot (pruned_decTreeModel, margin=0.1)
text (pruned_decTreeModel)

predictedLabelsPrune = predict(pruned_decTreeModel, testingSet, type="class")
sizeTestSet = dim(testingSet) [1]
errorTree = sum(predictedLabelsPrune != testingSet$class)
misclassification_rateTree = errorTree/sizeTestSet
```

```{r}
mushroomDataRF = read.csv("mushroom.csv", sep = ';')
head(mushroomDataRF)

library (rpart)

mushroomDataRF$class <- as.factor(mushroomDataRF$class)
mushroomDataRF$cap.shape <- as.numeric(as.factor(mushroomDataRF$cap.shape))
mushroomDataRF$cap.surface <- as.numeric(as.factor(mushroomDataRF$cap.surface))
mushroomDataRF$cap.color <- as.numeric(as.factor(mushroomDataRF$cap.color))
mushroomDataRF$does.bruise.or.bleed <- as.numeric(as.factor(mushroomDataRF$does.bruise.or.bleed))
mushroomDataRF$gill.attachment <- as.numeric(as.factor(mushroomDataRF$gill.attachment))
mushroomDataRF$gill.spacing <- as.numeric(as.factor(mushroomDataRF$gill.spacing))
mushroomDataRF$gill.color <- as.numeric(as.factor(mushroomDataRF$gill.color))
mushroomDataRF$stem.root <- as.numeric(as.factor(mushroomDataRF$stem.root))
mushroomDataRF$stem.surface <- as.numeric(as.factor(mushroomDataRF$stem.surface))
mushroomDataRF$stem.color <- as.numeric(as.factor(mushroomDataRF$stem.color))
mushroomDataRF$veil.type <- as.numeric(as.factor(mushroomDataRF$veil.type))
mushroomDataRF$veil.color <- as.numeric(as.factor(mushroomDataRF$veil.color))
mushroomDataRF$has.ring <- as.numeric(as.factor(mushroomDataRF$has.ring))
mushroomDataRF$ring.type <- as.numeric(as.factor(mushroomDataRF$ring.type))
mushroomDataRF$spore.print.color <- as.numeric(as.factor(mushroomDataRF$spore.print.color))
mushroomDataRF$habitat <- as.numeric(as.factor(mushroomDataRF$habitat))
mushroomDataRF$season <- as.numeric(as.factor(mushroomDataRF$season))

num_samples = dim(mushroomDataRF)[1]
sampling.rate = 0.8
training = sample(1:num_samples, sampling.rate*num_samples, replace= FALSE)
trainingSet = subset(mushroomDataRF[training, ])
testing = setdiff(1:num_samples,training)
testingSet = subset(mushroomDataRF[testing, ])

library(randomForest)

RandForestModel <- randomForest(class~.,data=trainingSet, ntree=100) 
plot(RandForestModel)
RandForestModel$err.rate

predictedLabels = predict(RandForestModel, testingSet, type ="class")
sizeTestSetRF = dim(testingSet)[1]
errorRF = sum(predictedLabels!=testingSet$class)
misclassRF = errorRF/sizeTestSetRF

IsE = (predictedLabels == 'e')
IsWrongAndE = (IsE & errorRF)
errorE = sum(IsWrongAndE)
```

```{r}
library(class)
mushroomDataKNN = read.csv("mushroom.csv", sep = ';')

mushroomDataKNN$cap.shape <- as.numeric(as.factor(mushroomDataKNN$cap.shape))
mushroomDataKNN$cap.surface <- as.numeric(as.factor(mushroomDataKNN$cap.surface))
mushroomDataKNN$cap.color <- as.numeric(as.factor(mushroomDataKNN$cap.color))
mushroomDataKNN$does.bruise.or.bleed <- as.numeric(as.factor(mushroomDataKNN$does.bruise.or.bleed))
mushroomDataKNN$gill.attachment <- as.numeric(as.factor(mushroomDataKNN$gill.attachment))
mushroomDataKNN$gill.spacing <- as.numeric(as.factor(mushroomDataKNN$gill.spacing))
mushroomDataKNN$gill.color <- as.numeric(as.factor(mushroomDataKNN$gill.color))
mushroomDataKNN$stem.root <- as.numeric(as.factor(mushroomDataKNN$stem.root))
mushroomDataKNN$stem.surface <- as.numeric(as.factor(mushroomDataKNN$stem.surface))
mushroomDataKNN$stem.color <- as.numeric(as.factor(mushroomDataKNN$stem.color))
mushroomDataKNN$veil.type <- as.numeric(as.factor(mushroomDataKNN$veil.type))
mushroomDataKNN$veil.color <- as.numeric(as.factor(mushroomDataKNN$veil.color))
mushroomDataKNN$has.ring <- as.numeric(as.factor(mushroomDataKNN$has.ring))
mushroomDataKNN$ring.type <- as.numeric(as.factor(mushroomDataKNN$ring.type))
mushroomDataKNN$spore.print.color <- as.numeric(as.factor(mushroomDataKNN$spore.print.color))
mushroomDataKNN$habitat <- as.numeric(as.factor(mushroomDataKNN$habitat))
mushroomDataKNN$season <- as.numeric(as.factor(mushroomDataKNN$season))

class = mushroomDataKNN$class
mushroomDataKNN = subset(mushroomDataKNN, select = -c(class) )

for(i in 1:ncol(mushroomDataKNN)){
  mushroomDataKNN[,i] = (mushroomDataKNN[,i] - mean(mushroomDataKNN[,i]))/(sd(mushroomDataKNN[,i]))
}

mushroomDataKNN$class = class

misKNN = c(300)
inClass = c(300)

for (i in 1:300) {
    
  num_samples = dim(mushroomDataKNN)[1]
  sampling.rate = 0.8
  training <- sample(1:num_samples, sampling.rate * num_samples, replace=FALSE)
  trainingSet <- subset(mushroomDataKNN[training, ])
  testing <- setdiff(1:num_samples, training)
  testingSet <- subset(mushroomDataKNN[testing, ])
    
  trainingfeaturesKNN <- subset(trainingSet, select=c(-class))
  traininglabelsKNN <- trainingSet$class
  testingfeaturesKNN <- subset(testingSet, select=c(-class))
  
  predictedLabelsKNN = knn(trainingfeaturesKNN, testingfeaturesKNN,traininglabelsKNN,k=i)
  sizeTestSetKNN = dim(testingSet)[1]
  error = sum(predictedLabelsKNN != testingSet$class)
  misRateKNN=error/sizeTestSetKNN
  misKNN[i]=misRateKNN
  
  inClass[i] = sum(predictedLabelsKNN != testingSet$class & testingSet$class == "e" )
  
}
inClass
min(inClass)
BestK = which(misKNN == min(misKNN))
LowestError = min(misKNN)
```

```{r}
plot(misKNN)
plot(inClass)
```
